.github/workflows/test-auth.yml, CHANGELOG.md, arc_memory/__init__.py, arc_memory/auth/default_credentials.py, arc_memory/auth/github.py, arc_memory/cli/auth.py, arc_memory/ingest/adr.py, arc_memory/ingest/github.py, arc_memory/sql/db.py, docs/api/db.md, docs/examples/sdk-usage.md, docs/guides/adr-formatting.md, docs/guides/troubleshooting.md, pyproject.toml, tests/auth/test_github_app_auth.py, tests/auth/test_github_auth.py, tests/ingest/test_adr_date_parsing.py, tests/validation/test_database.py
This PR addresses the issues reported in #6 by implementing several improvements:
- Fixed Device Flow API endpoints
- Added fallback mechanism for GitHub authentication
- Improved error messages with clear guidance
- Added `ensure_connection()` function to handle both paths and connections
- Updated core database functions to accept either paths or connections
- Added better error messages with actionable hints
- Improved date parsing with better error messages
- Added comprehensive tests for date parsing
- Added detailed documentation on ADR formatting
- Enhanced examples with proper connection handling
- Added troubleshooting section for common issues
- Created comprehensive API documentation for database functions
- Bumped version to 0.2.0
- Updated CHANGELOG.md with the changes
Fixes …
=> Fix API and Database Connection Issues

arc_memory/ingest/github_fetcher.py, tests/unit/test_github_fetcher.py, tests/unit/test_github_ingestor.py
This PR implements Phase 2 of the GitHub ingestion feature. It builds on Phase 1 by adding PR and issue fetching with GraphQL.
- Created `github_fetcher.py` with a GitHubFetcher class that:
- Fetches PRs and issues using GraphQL
- Fetches additional PR and issue details using REST API
- Creates PR and issue nodes from the fetched data
- Extracts mentions from PR and issue bodies and comments
- Creates mention edges between nodes
- Provides synchronous wrappers for async methods
- Updated the GitHub ingestor to use the new fetcher
- Added comprehensive unit tests for the fetcher and ingestor
All tests are passing. The implementation includes:
- Unit tests for the GitHubFetcher class
- Unit tests for the GitHubIngestor class with the new fetcher
- Tests for error handling, pagination, and …
=> GitHub Ingestion Phase 2: PR and Issue Fetching with GraphQL

.github/workflows/test-github-ingestion.yml, .gitignore, arc_memory/ingest/github.py, arc_memory/ingest/github_fetcher.py, arc_memory/ingest/github_graphql.py, arc_memory/ingest/github_rest.py, docs/github_integration.md, tests/integration/test_github_api_integration.py, tests/integration/test_github_incremental_build.py, tests/unit/test_github_fetcher.py, tests/unit/test_github_rest.py, tests/unit/test_github_rest_integration.py
This PR implements Phase 3 of the GitHub ingestion feature, focusing on REST API integration for specific operations.
- Enhanced the GitHub REST client with:
- Proper rate limit handling with retry limits to prevent infinite loops
- Backoff strategies for various error conditions
- Batch processing capabilities for better performance
- Additional methods for fetching PR and issue details
- Added new methods to fetch:
- PR commits
- PR review comments
- Issue events
- Issue timeline
- Batch PR and issue details
- Added focused integration tests for the REST client
Added integration tests that can be run with a valid GitHub token to verify the functionality works against the real GitHub API.
With this PR, the GitHub ingestion feature is complete with all three phases implemented.
=> GitHub Ingestion Phase 3: REST API Integration

arc_memory/attestation/__init__.py, arc_memory/cli/__init__.py, arc_memory/cli/sim.py, arc_memory/simulate/__init__.py, arc_memory/simulate/causal.py, arc_memory/simulate/diff_utils.py, tests/unit/simulate/__init__.py, tests/unit/simulate/test_diff_utils.py
This PR implements the first two steps of the `arc sim` command as outlined in our implementation plan. The `arc sim` command will enable simulation-based impact prediction by analyzing code diffs, running targeted fault injection experiments in isolated sandbox environments, and providing risk assessments with attestation.
- Created the basic Typer command structure for `arc sim`
- Implemented argument parsing and validation
- Set up the directory structure for simulation modules
- Added a `list-scenarios` subcommand for better developer experience
- Implemented diff extraction from Git using GitPython
- Added support for pre-serialized diff JSON
- Created a simple mapping of files to services
- Added placeholder for causal graph derivation
- Manual testing of the command with default …
=> feat(cli): Implement arc sim command structure and diff analysis

arc_memory/cli/sim.py, arc_memory/simulate/code_interpreter.py, arc_memory/simulate/fault_driver.py, tests/unit/simulate/test_fault_driver.py
This PR implements Step 6 of our implementation plan: Implement Fault Injection. It adds functionality to apply fault injection experiments, monitor the system during fault injection, and collect metrics and logs.
- Create `fault_driver.py` for fault injection
- Implement `FaultDriver` class for applying and monitoring fault experiments
- Add functions to apply network latency faults using Chaos Mesh
- Add functions to monitor the system during fault injection
- Add functions to collect metrics and logs
- Update `code_interpreter.py` to use the fault driver
- Update CLI to extract more metrics from the fault driver
- Add comprehensive unit tests for the fault driver
All tests pass, including the new unit tests for the fault driver implementation.
Part of the `arc sim` command …
=> feat: implement fault injection driver

arc_memory/cli/sim.py, arc_memory/simulate/langgraph_flow.py, docs/memory_integration.md, tests/unit/simulate/test_langgraph_flow.py
This PR implements Step 7 of our implementation plan: Implement LangGraph Workflow. It adds functionality to orchestrate the simulation workflow using LangGraph, defining the steps, handling state passing between steps, and managing the overall simulation process.
- Create `langgraph_flow.py` for orchestrating the simulation workflow
- Implement functions to define workflow steps
- Implement functions to handle state passing between steps
- Implement functions to manage the overall simulation process
- Update CLI to use LangGraph workflow when available
- Add comprehensive unit tests for the LangGraph workflow
All tests pass, including the new unit tests for the LangGraph workflow implementation.
Part of the `arc sim` command implementation.
---
Pull Request opened by [Augment …
=> feat: implement LangGraph workflow

.env.example, .github/workflows/test-auth.yml, .github/workflows/test-github-ingestion.yml, arc_memory/attestation/__init__.py, arc_memory/attestation/write_attest.py, arc_memory/simulate/__init__.py, arc_memory/simulate/explanation.py, arc_memory/simulate/langgraph_flow.py, pyproject.toml, tests/conftest.py, tests/integration/test_version.py, tests/unit/attestation/test_write_attest.py, tests/unit/simulate/test_code_interpreter.py, tests/unit/simulate/test_explanation.py, tests/unit/simulate/test_langgraph_flow.py, tests/unit/test_github_rest_integration.py
This PR implements Step 8 of the Arc Sim implementation plan:
1. Created modules for analyzing simulation results and generating attestation
2. Implemented functions to:
- Process collected metrics
- Calculate risk scores
- Generate human-readable explanations
- Create attestation JSON with cryptographic verification
- Added `arc_memory/simulate/explanation.py` with functions for processing metrics, calculating risk scores, and generating human-readable explanations
- Added `arc_memory/attestation/write_attest.py` with functions for creating and verifying cryptographically signed attestations
- Updated the LangGraph workflow to use the new modules
- Added comprehensive tests for the new functionality
All tests are passing for the new modules.
---
Pull Request opened by [Augment …
=> Implement Results Analysis and Attestation

README.md, arc_memory/simulate/mocks.py, docs/cli/sim.md, docs/examples/simulation.md, tests/cli/test_sim.py, tests/conftest.py, tests/integration/test_sim_command.py, tests/integration/test_sim_github_integration.py, tests/unit/simulate/test_mocks.py
This PR implements Step 9 of the Arc Sim implementation plan, adding comprehensive tests for the simulation functionality.
- Added CLI tests in `tests/cli/test_sim.py` to test argument parsing, validation, and command execution
- Created mock implementations and tests in `tests/unit/simulate/test_mocks.py` for E2B and Chaos Mesh
- Created end-to-end tests in `tests/integration/test_sim_command.py` to test the full workflow
- Created GitHub integration tests in `tests/integration/test_sim_github_integration.py`
- Added comprehensive test fixtures in `tests/conftest.py` for diffs, causal graphs, manifests, metrics, and more
- Created mock implementations in `arc_memory/simulate/mocks.py` for E2B and Chaos Mesh
All tests are now passing, providing good coverage for the Arc Sim …
=> Add comprehensive tests for Arc Sim implementation

arc_memory/auth/linear.py, arc_memory/cli/auth.py, arc_memory/cli/build.py, arc_memory/errors.py, arc_memory/ingest/adr.py, arc_memory/ingest/linear.py, arc_memory/plugins.py
This PR implements the initial Linear integration for Arc Memory, focusing on Milestone 1 of the Arc Memory PR Bot v0.1 sprint.
- Added Linear authentication module with API key support
- Added secure token storage in keyring
- Added `arc auth linear` CLI command
- Created LinearIngestor for GraphQL API integration
- Implemented node and edge creation for Linear issues
- Added proper error handling and logging
- Updated glob pattern to scan `docs/adr-*.md` files
- Added `--linear` flag to `arc build` command (simplified from `--with-linear`)
- Implemented plugin filtering based on flags
- Added support for incremental updates
The implementation has been tested with a Linear API key and successfully ingests issues into the knowledge graph.
- Currently only supports API key authentication, …
=> Linear Integration (API Key Auth)

.github/workflows/test-auth.yml, arc_memory/auth/default_credentials.py, arc_memory/auth/linear.py, arc_memory/cli/auth.py, arc_memory/ingest/linear.py, docs/cli/auth.md, docs/dev/linear-oauth.md, docs/troubleshooting/linear-oauth.md, tests/auth/test_linear_auth.py, tests/auth/test_linear_oauth_flow.py
This PR implements the full OAuth 2.0 flow for Linear authentication, replacing the current API key-based authentication with a more secure and user-friendly approach.
- Enhanced LinearAppConfig model to include OAuth-specific fields
- Added LinearOAuthToken model for OAuth token storage
- Updated environment variable handling to support OAuth configuration
- Implemented secure storage for OAuth tokens in the keyring with encryption
- Implemented authorization URL generation with proper parameters
- Created a local callback server to receive the authorization code
- Added state parameter verification to prevent CSRF attacks
- Implemented token exchange functionality
- Added token validation and expiration handling
- Implemented token revocation for logout functionality
- Updated the …
=> Linear OAuth 2.0 Integration

README.md
- Add Linear authentication step to Quick Start Workflow
- Update build command examples to include Linear integration
- Add Linear authentication troubleshooting information
- Update numbering in Quick Start Workflow steps
=> Update README.md with Linear OAuth authentication information

arc-memory-pr-bot/package.json, arc-memory-pr-bot/src/graph-service.ts, arc-memory-pr-bot/src/index.ts, arc-memory-pr-bot/src/mock-graph-data.ts, arc-memory-pr-bot/src/mock-graph-service.ts, arc-memory-pr-bot/test/graph-service.test.ts, arc-memory-pr-bot/test/index.test.ts
This PR implements Issue 2: Knowledge Graph Integration Layer for the PR Bot. It creates a layer that allows the PR Bot to query the Arc Memory knowledge graph, enabling it to extract context about PRs, related Linear tickets, and architectural decisions.
- Created a `GraphService` class that interfaces with the SQLite database
- Implemented query methods for:
- Finding Linear tickets related to a PR/branch
- Retrieving ADRs related to changed files
- Extracting commit history and context
- Finding related PRs for files
- Added caching to improve performance
- Implemented error handling and logging
- Created mock data and services for testing
- Added comprehensive tests
The `GraphService` class provides a clean interface to query the knowledge graph. It connects to the SQLite database …
=> Create Knowledge Graph Integration Layer for PR Bot

README.md, arc_memory/cli/why.py, arc_memory/llm/ollama_client.py, arc_memory/semantic_search.py, docs/cli/why.md, tests/cli/test_why.py, tests/unit/test_semantic_search.py
This PR implements a multi-stage prompting approach for the `Arc Why` natural language query functionality. The system now breaks down complex queries into specialized components:
1. Query Understanding - Interprets user intent and extracts key search parameters
2. Knowledge Graph Search - Performs targeted graph traversals based on semantic understanding
3. Response Generation - Creates coherent narratives from search results
Key improvements:
- Distinct system prompts for each processing stage, optimizing LLM performance
- Two-stage query intent processing for better accuracy
- Robust error handling for database queries and LLM connectivity
- Detailed debugging system with configurable logging levels
- Fixed node attribute access in knowledge graph search
This implementation follows the …
=> Arc search

arc_memory/cli/why.py, arc_memory/semantic_search.py
This PR addresses two code review feedback items:
1. **Removed redundant conditional check in JSON extraction**
- Eliminated duplicate condition checking in `semantic_search.py`
- Streamlined the JSON extraction logic for better readability
2. **Improved defensive programming in markdown generation**
- Replaced direct dictionary access with `.get()` method calls
- Added default values to prevent KeyError exceptions
- Added empty list default for `decision_makers` field to avoid errors when joining
These changes make the code more robust when handling incomplete data structures and fix logical redundancy.
=> Fix code review feedback items

arc_memory/cli/__init__.py, arc_memory/cli/migrate.py, arc_memory/ingest/github.py, arc_memory/ingest/github_fetcher.py, arc_memory/llm/ollama_client.py, arc_memory/migrations/__init__.py, arc_memory/migrations/add_timestamp_column.py, arc_memory/process/temporal_analysis.py, arc_memory/sql/db.py, arc_memory/utils/__init__.py, arc_memory/utils/temporal.py, auto.md, tests/legacy/unit/simulate/test_explanation.py, tests/legacy/unit/simulate/test_fault_driver.py, tests/legacy/unit/simulate/test_langgraph_flow.py, tests/legacy/unit/simulate/test_manifest.py, tests/legacy/unit/simulate/test_memory_integration.py, tests/legacy/unit/simulate/test_mocks.py, tests/utils/__init__.py, tests/utils/test_temporal.py
This PR implements temporal data alignment in the schema, ensuring that temporal data is properly indexed for efficient querying. This is a critical foundation for the auto-refresh functionality.
1. **Added Temporal Utilities**:
- Implemented `normalize_timestamp` function to extract timestamps from different node types
- Added `parse_timestamp` function to parse timestamps from various formats
- Added `get_timestamp_str` function to convert timestamps to ISO-formatted strings
- Added `compare_timestamps` function to compare timestamps
2. **Updated Database Schema**:
- Added a dedicated `timestamp` column to the `nodes` table
- Created an index on the `timestamp` column for efficient querying
- Updated database operations to handle the new column
3. **Created Migration Script**:
- …
=> Implement Temporal Data Alignment in Schema

arc_memory/db/__init__.py, arc_memory/db/base.py, arc_memory/db/metadata.py, arc_memory/db/neo4j_adapter.py, arc_memory/db/sqlite_adapter.py, tests/unit/test_db_adapters.py, tests/unit/test_db_metadata.py, tests/unit/test_neo4j_adapter.py
This PR implements a database abstraction layer and metadata utilities for the auto-refresh functionality.
1. **Database Abstraction Layer**:
- Created `arc_memory/db/base.py` with abstract base classes for database operations
- Defined `DatabaseAdapter` protocol with required methods
- Created methods for metadata storage and retrieval
- Designed with both SQLite and Neo4j compatibility in mind
2. **SQLite Adapter**:
- Implemented the `DatabaseAdapter` interface in `arc_memory/db/sqlite_adapter.py`
- Ensured all database operations go through this adapter
- Added transaction support for atomic updates
3. **Neo4j Adapter**:
- Created stub implementation in `arc_memory/db/neo4j_adapter.py`
- Implemented interface with placeholder methods
- Added feature flag to control adapter selection
4. …
=> Database Abstraction Layer and Metadata Utilities

.github/workflows/test-cli-commands.yml, arc_memory/auto_refresh/__init__.py, arc_memory/auto_refresh/core.py, arc_memory/auto_refresh/sources/__init__.py, arc_memory/auto_refresh/sources/adr.py, arc_memory/auto_refresh/sources/github.py, arc_memory/auto_refresh/sources/linear.py, arc_memory/cli/__init__.py, arc_memory/cli/refresh.py, arc_memory/cli/relate.py, arc_memory/cli/why.py, arc_memory/config.py, arc_memory/db/metadata.py, arc_memory/errors.py, arc_memory/process/temporal_analysis.py, arc_memory/scheduler.py, arc_memory/sql/db.py, tests/cli/test_relate.py, tests/cli/test_why.py, tests/integration/test_auto_refresh.py, tests/integration/test_enhanced_knowledge_graph.py, tests/unit/test_auto_refresh.py, tests/unit/test_temporal_analysis.py
This PR implements the auto-refresh functionality for Arc Memory, as outlined in the auto.md roadmap document.
- Added core auto-refresh module with functions for checking and performing refreshes
- Implemented metadata storage for tracking refresh timestamps
- Added CLI commands for manual and scheduled refreshes
- Implemented GitHub source refresh functionality
- Added integration tests for auto-refresh functionality
All integration tests are passing. The CLI commands have been manually tested and are working correctly.
---
Pull Request opened by [Augment Code](https://www.augmentcode.com/) with guidance from the PR author
=> Implement auto-refresh functionality

arc_memory/sdk/__init__.py, arc_memory/sdk/adapters/__init__.py, arc_memory/sdk/adapters/base.py, arc_memory/sdk/adapters/registry.py, arc_memory/sdk/core.py, arc_memory/sdk/errors.py, arc_memory/sdk/models.py, tests/unit/test_sdk_core.py
This PR implements the first part of the SDK refactoring plan as outlined in `docs/roadmap/sdk_refactoring_plan.md`. It establishes the foundation for the Arc Memory SDK by creating the core `Arc` class, integrating with existing database adapters, defining return types, and implementing the framework adapter protocol.
- Created the `Arc` class as the main entry point with `repo_path` and optional `adapter_type` parameters
- Integrated with existing database adapters through the `DatabaseAdapter` protocol
- Implemented core methods like `get_node_by_id()` and `add_nodes_and_edges()`
- Added context manager support for clean resource management
- Created `QueryResult` for natural language queries
- Implemented `EntityDetails` for node information with relationships
- …
=> SDK Core Implementation (PR #1)

arc_memory/cli/relate.py, arc_memory/cli/why.py, arc_memory/sdk/cache.py, arc_memory/sdk/core.py, arc_memory/sdk/decision_trail.py, arc_memory/sdk/impact.py, arc_memory/sdk/models.py, arc_memory/sdk/progress.py, arc_memory/sdk/query.py, arc_memory/sdk/relationships.py, arc_memory/sdk/temporal.py, docs/roadmap/sdk_refactoring_plan.md, tests/cli/test_relate.py, tests/cli/test_why.py, tests/sdk/__init__.py, tests/sdk/test_cache.py, tests/sdk/test_decision_trail.py, tests/sdk/test_impact.py, tests/sdk/test_progress.py, tests/sdk/test_query.py, tests/sdk/test_relationships.py, tests/sdk/test_temporal.py, tests/unit/test_relate_filtering.py
This PR implements PR 2a of the SDK refactoring plan, which focuses on extracting query functionality from CLI commands into the SDK.
1. **Enhanced Query API**
- Natural language queries about the codebase
- Focus on causal relationships and decision trails
- Support for caching and progress reporting
2. **Enhanced Decision Trail API**
- Trace history for specific file lines
- Extract decision rationales
- Support for caching and progress reporting
3. **Enhanced Entity Relationship API**
- Get entities related to a specific entity
- Filter by relationship type and direction
- Include edge properties in results
4. **Component Impact API (Blast Radius)**
- Analyze potential impact of changes
- Identify affected components
- Support for different impact types
5. **Temporal Analysis API**
- …
=> PR 2a: Extract query functionality from CLI commands into the SDK

arc_memory/cli/export.py, arc_memory/sdk/core.py, arc_memory/sdk/errors.py, arc_memory/sdk/export.py, arc_memory/sdk/models.py, tests/integration/test_export_command.py, tests/sdk/test_export.py
This PR implements the second part of the SDK refactoring plan, extracting export functionality from CLI commands into the SDK.
1. **Created Export SDK Module**:
- Created `arc_memory/sdk/export.py` with the core export functionality extracted from the CLI commands.
- Implemented the `export_knowledge_graph` function that handles exporting the knowledge graph to various formats, with support for filtering, compression, and signing.
2. **Defined Export-Related Models**:
- Added the `ExportResult` model to `arc_memory/sdk/models.py` to represent the result of an export operation.
- Added the `ExportSDKError` class to `arc_memory/sdk/errors.py` to handle export-related errors.
3. **Added Export Methods to Arc Class**:
- Added the `export_graph` method to the `Arc` class in …
=> PR 2b: Extract export functionality from CLI commands into SDK

arc_memory/sdk/adapters/__init__.py, arc_memory/sdk/adapters/langchain.py, arc_memory/sdk/adapters/openai.py, arc_memory/sdk/adapters/registry.py, pyproject.toml, tests/sdk/test_adapters.py, tests/sdk/test_arc_adapters.py
This PR updates the framework adapters to align with the latest documentation and best practices for both OpenAI and LangChain.
- Updated to support the newer OpenAI API (v1.0.0+) with the appropriate structure for tool calling
- Added support for the OpenAI Assistants API
- Updated default model to "gpt-4o" and added support for newer models
- Enhanced message handling to support both string queries and structured message arrays
- Added support for the newer LangGraph approach to agents, with fallback to legacy AgentExecutor
- Updated imports to work with both older and newer versions of LangChain
- Added support for chat memory in both LangGraph and legacy agents
- Updated to use the newer tool calling pattern
- Replaced the deprecated `pkg_resources` module with the modern …
=> Update framework adapters for OpenAI and LangChain

README.md, arc_memory/sdk/adapters/langchain.py, arc_memory/sdk/adapters/openai.py, docs/examples/component_impact_analysis.md, docs/examples/sdk_examples.md, docs/getting_started.md, docs/quickstart.md, docs/sdk/README.md, docs/sdk/adapters.md, docs/sdk/api_reference.md
This PR addresses critical documentation inconsistencies and usability issues identified during a comprehensive QA analysis of the Arc Memory SDK. The changes focus on improving the developer experience, especially for first-time users, by ensuring documentation matches implementation and providing clear, consistent examples.
Additionally, this PR implements significant improvements to the framework adapters, adding streaming support for OpenAI, better compatibility with the latest LangChain versions, and standardized error handling across all methods.
- Fixed class name inconsistencies (standardized on `Arc` instead of `ArcMemory`)
- Fixed parameter naming inconsistencies (`enhance_for_llm` vs `optimize_for_llm`)
- Updated return type documentation to match actual implementation …
=> SDK QA Fixes: Documentation and Framework Adapter Improvements

arc_memory/db/sqlite_adapter.py, arc_memory/sdk/core.py, arc_memory/sdk/errors.py, arc_memory/sdk/export.py, tests/qa/qa_test_adapters.py, tests/qa/qa_test_functionality.py
This PR fixes several critical issues identified during QA testing for version 0.5.0:
1. **SQLiteAdapter Missing Method**: Implemented the `execute_query` method in the SQLiteAdapter class, which was missing and causing tests to fail.
2. **SDKError Initialization Issue**: Fixed the SDKError constructor by making the `message` parameter optional with a default empty string value, resolving the initialization error.
3. **Export Graph Path Issue**: Updated the export_graph method in the Arc class to use the SDK's export_knowledge_graph function instead of the older export_graph_impl function, which was causing the 'output_path' attribute error.
4. **Test Improvements**: Improved the QA test files to handle edge cases better, particularly for component impact analysis and export …
=> Fix QA test issues for version 0.5.0

arc_memory/auto_refresh/core.py, arc_memory/db/sqlite_adapter.py, arc_memory/migrations/add_architecture_schema.py, arc_memory/migrations/add_repo_id_column.py, arc_memory/process/architecture_extraction.py, arc_memory/schema/models.py, arc_memory/sdk/core.py, docs/api/models.md, docs/sdk/api_reference.md, pyproject.toml, tests/integration/test_repository_architecture_integration.py, tests/unit/schema/test_repository_architecture_models.py, tests/unit/test_architecture_extraction.py, tests/unit/test_architecture_queries.py, tests/unit/test_llm_integration.py, tests/unit/test_openai_enhancement.py, tests/unit/test_repository_management.py, tests/unit/test_sdk_core.py, tests/unit/test_semantic_search.py
This PR adds repository identity and architecture schema features to Arc Memory, enabling multi-repository support and architecture modeling.
- Added repository identity features:
- Created a migration script for repository identity
- Updated the SQLite adapter to run the migration automatically
- Added repository management methods to the SDK
- Added architecture schema features:
- Added new node types: System, Service, Component, Interface
- Added new edge relationships: CONTAINS, EXPOSES, CONSUMES, COMMUNICATES_WITH
- Fixed architecture extraction to include required fields
- Added comprehensive tests:
- Unit tests for repository identity models
- Unit tests for architecture schema models
- Unit tests for repository management methods
- Unit tests for architecture extraction
- Unit …
=> Add repository identity and architecture schema features

arc_memory/sdk/temporal.py, demo/code_time_machine/README.md, demo/code_time_machine/__init__.py, demo/code_time_machine/code_time_machine.py, demo/code_time_machine/custom_impact.py, demo/code_time_machine/reasoning_engine.py, demo/code_time_machine/run_demo.sh, demo/code_time_machine/sample_queries.json, demo/code_time_machine/visualizers/__init__.py, demo/code_time_machine/visualizers/decision_visualizer.py, demo/code_time_machine/visualizers/impact_visualizer.py, demo/code_time_machine/visualizers/timeline_visualizer.py
This PR adds a new Code Time Machine demo that showcases Arc Memory's temporal understanding capabilities. The demo allows users to explore how code evolved over time, understand the reasoning behind key decisions, and visualize the potential impact of changes.
- **Timeline Exploration**: Shows how a file evolved over time with ASCII/Unicode-based timeline
- **Decision Archaeology**: Explores key decisions with rich formatting for commit history, PRs, and rationales
- **Impact Prediction**: Visualizes potential impacts with color-coded risk assessment
- **Improvement Suggestions**: Generates suggestions based on historical patterns
- **OpenAI Reasoning Model Integration**: Uses o4-mini model to provide advanced analysis with reasoning traces
```bash
./demo/code_time_machine/run_demo.sh …
```
=> Add Code Time Machine demo with OpenAI reasoning model integration

arc_memory/sdk/impact.py, tests/sdk/test_impact.py
Closes #68
This PR implements a dynamic scoring system for impact analysis that considers multiple factors beyond simple dependency relationships:
1. **Relationship Strength**
- Calculate scores based on relationship type (DEPENDS_ON, IMPORTS, USES, etc.)
- Consider edge properties like frequency and confidence
- Adjust for source and target node characteristics
2. **Component Importance**
- Evaluate importance based on node type (ADR, ISSUE, PR, FILE, etc.)
- Consider centrality in the graph (number of connections)
- Factor in historical significance when available
3. **Architectural Context**
- Detect system and service boundary crossings
- Apply penalties for cross-boundary dependencies
- Recognize critical components and paths
4. **Co-Change Patterns**
- Implement full co-change …
=> Enhance Impact Analysis with Dynamic Scoring System

.gitignore, arc_memory/rl/agent.py, arc_memory/rl/environment.py, arc_memory/rl/run.py, docs/rl/PR_DESCRIPTION.md
This pull request refactors the reinforcement learning (RL) agents and environment in the `arc_memory` module to replace the concept of "node IDs" with "component IDs." This change aligns the RL framework with a more modular architecture by focusing on components instead of nodes in the knowledge graph. Additionally, it introduces improvements to the environment's state representation and action handling.
* [`arc_memory/rl/agent.py`](diffhunk://#diff-c8c28ff01eb1025c761ce00e8dd9508abc1faafbf7915255c9051a790db92c05L77-R86): Updated `RandomAgent` and `QTableAgent` classes to use `component_ids` instead of `node_ids` in their initialization, action generation, and action handling logic. This includes changes to methods like `act`, `_create_action_space`, and `_action_to_key`. …
=> Updated baseline RL pipeline with Q-learning for blast radius prediction

demo/README.md, demo/blast_radius_demo.py, demo/code_relationships_demo.py, demo/knowledge_query_demo.py
- Added `demo/github-actions-workflow.yml` with a complete workflow that:
- Runs on pushes to main and merged PRs
- Builds or refreshes the knowledge graph
- Uses o4-mini for LLM enhancement
- Analyzes the impact of changes for merged PRs
- Uploads the graph and impact report as artifacts
- Added `demo/github-actions-readme.md` with detailed setup instructions
- Validated the GitHub Actions workflow format
=> Starter Kit: Add Examples & GitHub Actions workflow demo

CHANGELOG.md, arc_memory/__init__.py, arc_memory/cli/build.py, arc_memory/db/sqlite_adapter.py, arc_memory/llm/openai_client.py, arc_memory/migrations/add_enhanced_schema.py, arc_memory/process/semantic_analysis.py, arc_memory/schema/models.py, arc_memory/semantic_search.py, demo/knowledge_query_demo.py, pyproject.toml, tests/test_enhanced_schema.py, tests/unit/test_enhanced_schema.py
This PR implements an enhanced schema for the knowledge graph to provide a stronger foundation for users to build on top of with the SDK.
- Added temporal tracking fields: `created_at`, `updated_at`, `valid_from`, `valid_until`
- Added enhanced metadata fields: `metadata` (renamed from `extra`), `embedding`, `url`
- Added backward compatibility for the `extra` field
- Added new columns to the `nodes` table
- Added indices for the new fields
- Updated serialization/deserialization logic
- Created a migration script to add new columns to existing databases
- Migrates data from existing fields to new fields
- Added tests to verify the enhanced schema functionality
- Ensured backward compatibility with existing code
This PR is fully compatible with the multi-repository support implemented in …
=> Enhanced Schema for Knowledge Graph

CHANGELOG.md, arc_memory/__init__.py, arc_memory/sdk/core.py, arc_memory/sdk/query.py, pyproject.toml
This PR implements high-impact, low-complexity improvements to the Arc Memory SDK to make it more production-ready for developers.
Added two new methods to the `Arc` class:
- `is_graph_valid()`: Checks if the knowledge graph exists and has the expected structure
- `get_graph_statistics()`: Provides insights into the size and composition of the graph
These methods will help developers understand the state of their knowledge graph and diagnose issues more easily.
Standardized the confidence scores in the query functionality to consistently use a 0.0-1.0 scale. Previously, the scores were on a 1-10 scale in some places and 0.0-1.0 in others, which could lead to confusion.
Improved error messages across the SDK to provide more specific guidance on how to resolve issues:
- Added detailed error …
=> SDK Improvements: Health Check Methods, Standardized Confidence Scores, and Enhanced Error Messages

.gitignore, arc_memory/rl/README.md, arc_memory/rl/benchmark.py, arc_memory/rl/data_provider.py, arc_memory/rl/environment.py, arc_memory/rl/reward.py, arc_memory/rl/run.py
This pull request refactors and enhances the reinforcement learning (RL) pipeline for predicting the blast radius of code changes. Key updates include significant changes to the documentation, a streamlined reward system, and the introduction of a benchmarking tool for evaluating the RL pipeline across different configurations and datasets.
* Updated `README.md` to reflect a new focus on blast radius prediction, simplifying the description of components and usage instructions. Removed outdated multi-component reward function details and added instructions for benchmarking and evaluation.
* Introduced `arc_memory/rl/benchmark.py` to provide benchmarking utilities for the RL pipeline. Includes methods for evaluating performance across timeframes, sensitivity to reward thresholds, and …
=> Implemented the binary reward system
